name: String Tests

on:
  # Every 15th of the month at midnight
  schedule:
    - cron: "0 0 15 * *"
  # Manually triggered
  workflow_dispatch:

jobs:
  string-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgmp-dev libeigen3-dev libboost-all-dev
    
    - name: Build string tests
      run: |
        cd src_basic
        make Test_String_Split Test_String_Trim Test_String_Conversion Test_String_Optimization Test_Basic_string_Optimizations Test_Namelist_Substr
    
    - name: Test_String_Split
      run: cd src_basic && ./Test_String_Split
    
    - name: Test_String_Trim
      run: cd src_basic && ./Test_String_Trim
    
    - name: Test_String_Conversion
      run: cd src_basic && ./Test_String_Conversion
    
    - name: Test_String_Optimization
      run: cd src_basic && ./Test_String_Optimization
    
    - name: Test_Basic_string_Optimizations
      run: cd src_basic && ./Test_Basic_string_Optimizations
    
    - name: Test_Namelist_Substr
      run: cd src_basic && ./Test_Namelist_Substr